import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
import { GoogleGenAI, Modality } from '@google/genai';

// Initialize Firebase Admin
admin.initializeApp();

// Get Gemini API key from environment
const GEMINI_API_KEY = functions.config().gemini?.api_key || process.env.GEMINI_API_KEY;

if (!GEMINI_API_KEY) {
  console.error('GEMINI_API_KEY is not configured. AI features will not work.');
}

// Initialize Gemini AI client
let ai: GoogleGenAI | null = null;
if (GEMINI_API_KEY) {
  ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
}

const getAi = () => {
  if (!ai) {
    throw new functions.https.HttpsError(
      'failed-precondition',
      'Gemini AI client is not initialized. Please check your API key configuration.'
    );
  }
  return ai;
};

// Helper function to verify admin access
async function verifyAdmin(context: functions.https.CallableContext): Promise<void> {
  if (!context.auth) {
    throw new functions.https.HttpsError(
      'unauthenticated',
      'The function must be called while authenticated.'
    );
  }

  // Get admin email from environment or use default
  const adminEmail = functions.config().admin?.email || process.env.ADMIN_EMAIL || 'admin@example.com';
  
  if (context.auth.token.email !== adminEmail) {
    throw new functions.https.HttpsError(
      'permission-denied',
      'Only admin users can call this function.'
    );
  }
}

/**
 * Cloud Function: generateContent
 * Generates text content using Gemini AI
 * For summarize operations: public access (no auth required)
 * For content creation: requires admin authentication
 */
export const generateContent = functions.https.onCall(async (data, context) => {
  const { prompt, systemInstruction, isPublic } = data;

  // Check if this is a public operation (like summarize)
  // If not public, require admin authentication
  if (!isPublic) {
    // For non-public operations, require authentication
    if (!context.auth) {
      throw new functions.https.HttpsError(
        'unauthenticated',
        'The function must be called while authenticated for this operation.'
      );
    }
    await verifyAdmin(context);
  }
  // If isPublic is true, allow unauthenticated calls (no check needed)

  if (!prompt || typeof prompt !== 'string') {
    throw new functions.https.HttpsError(
      'invalid-argument',
      'The function must be called with a valid prompt string.'
    );
  }

  try {
    const response = await getAi().models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      ...(systemInstruction && {
        config: {
          systemInstruction,
        },
      }),
    });

    return { text: response.text };
  } catch (error) {
    console.error('Error calling Gemini API:', error);
    throw new functions.https.HttpsError(
      'internal',
      'An error occurred while generating content.',
      error
    );
  }
});

/**
 * Cloud Function: generateImageFromPrompt
 * Generates an image using Gemini AI
 * Requires admin authentication
 */
export const generateImageFromPrompt = functions.https.onCall(async (data, context) => {
  await verifyAdmin(context);

  const { prompt } = data;

  if (!prompt || typeof prompt !== 'string') {
    throw new functions.https.HttpsError(
      'invalid-argument',
      'The function must be called with a valid prompt string.'
    );
  }

  try {
    const response = await getAi().models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: `A high-quality, professional blog post image for an article titled: "${prompt}"`,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData && part.inlineData.data) {
        const base64ImageBytes: string = part.inlineData.data;
        const mimeType = part.inlineData.mimeType || 'image/png';
        const imageUrl = `data:${mimeType};base64,${base64ImageBytes}`;
        return { imageUrl };
      }
    }

    throw new functions.https.HttpsError(
      'internal',
      'No image was generated by the AI.'
    );
  } catch (error) {
    console.error('Error calling Gemini API for image generation:', error);
    throw new functions.https.HttpsError(
      'internal',
      'An error occurred while generating the image.',
      error
    );
  }
});

