import { GoogleGenAI, Modality } from "@google/genai";

// The environment variable is expected to be available.
const apiKey = process.env.GEMINI_API_KEY;

let ai: GoogleGenAI | null = null;
if (apiKey) {
  ai = new GoogleGenAI({ apiKey });
} else {
  console.error(
    "API_KEY environment variable not found. AI features will be disabled."
  );
}

const getAi = () => {
  if (!ai) {
    throw new Error(
      "Gemini AI client is not initialized. Please check your API key."
    );
  }
  return ai;
};

const handleError = (error: unknown): never => {
  console.error("Error calling Gemini API:", error);
  if (error instanceof Error && error.message.includes("API key not valid")) {
    throw new Error(
      "The provided API key is not valid. Please check your configuration."
    );
  }
  throw new Error(
    "An error occurred with the AI service. Please try again later."
  );
};

export async function generateContent(
  prompt: string,
  systemInstruction?: string
): Promise<string> {
  try {
    const response = await getAi().models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      ...(systemInstruction && {
        config: {
          systemInstruction,
        },
      }),
    });
    return response.text;
  } catch (error) {
    handleError(error);
  }
}

export async function generateImageFromPrompt(prompt: string): Promise<string> {
  try {
    const response = await getAi().models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: {
        parts: [
          {
            text: `A high-quality, professional blog post image for an article titled: "${prompt}"`,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        const mimeType = part.inlineData.mimeType;
        return `data:${mimeType};base64,${base64ImageBytes}`;
      }
    }
    throw new Error("No image was generated by the AI.");
  } catch (error) {
    handleError(error);
  }
}
